name: Dependabot PR automerge

on:
  pull_request_target:
    types: [ opened, reopened ]
    branches:
      - master

jobs:
  auto-merge:
    if: contains(github.actor, 'dependabot') # Run only if dependabot PR
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          config: .github/auto-merge.yml
          target: minor
          command: merge
          approve: 'true'
